[package]
name = "neort-dsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
neort-blocks = { workspace = true }

rtsan = { workspace = true }
realfft = { workspace = true }
num = { workspace = true }
ringbuf = { workspace = true }

[dev-dependencies]
rubato = "0.16.1"
