[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "neort-dsp"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
neort-blocks = { workspace = true }

num = { workspace = true }
realfft = { workspace = true }
ringbuf = { workspace = true }
rtsan = { workspace = true }

[dev-dependencies]
rubato = "0.16.1"
