[package]
name = "neort"
version = "0.0.0"
edition = "2021"
authors = ["Stephan Eckes <stephan@neodsp.com>"]
description = "neort is a framework for real-time audio applications"
repository = "https://github.com/neodsp/neort"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["neodsp", "audio", "dsp", "real-time"]
categories = ["multimedia::audio"]

[dependencies]
atomic_float = "1.1"
ndarray = "0.16"
num = "0.4"
realfft = "3.4"
ringbuf = "0.4"
rtsan = { git = "https://github.com/realtime-sanitizer/rtsan-standalone-rs", branch = "dev", features = [
    "sanitize",
] }

[dev-dependencies]
babycat = "0.0.15"
