[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "neort-blocks"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
num = { workspace = true }
rtsan = { workspace = true }

[features]
default = ["alloc"]

alloc = []
rtsan = ["rtsan/enable"]

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "blocks"
harness = false
