// The resamplers are copied from rubato by Henrik Enquist and adapted to take Blocks

use num::Float;

use crate::audio_block::{BlockRead, BlockWrite};

/// Different window functions that can be used to window the sinc function.
#[derive(Debug, Clone, Copy)]
#[allow(unused)]
pub enum WindowFunction {
    /// Blackman. Intermediate rolloff and intermediate attenuation.
    Blackman,
    /// Squared Blackman. Slower rolloff but better attenuation than Blackman.
    Blackman2,
    /// Blackman-Harris. Slow rolloff but good attenuation.
    BlackmanHarris,
    /// Squared Blackman-Harris. Slower rolloff but better attenuation than Blackman-Harris.
    BlackmanHarris2,
    /// Hann. Fast rolloff but not very high attenuation.
    Hann,
    /// Squared Hann. Slower rolloff and higher attenuation than simple Hann.
    Hann2,
}

/// Helper function. Standard Blackman-Harris window.
// The window created is periodic.
pub fn blackman_harris<T>(npoints: usize) -> Vec<T>
where
    T: Float,
{
    let mut window = vec![T::zero(); npoints];
    let pi2 = T::from(2.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let pi4 = T::from(4.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let pi6 = T::from(6.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let np_f = T::from(npoints).unwrap();
    let a = T::from(0.35875).unwrap();
    let b = T::from(0.48829).unwrap();
    let c = T::from(0.14128).unwrap();
    let d = T::from(0.01168).unwrap();
    for (x, item) in window.iter_mut().enumerate() {
        let x_float = T::from(x).unwrap();
        *item = a - b * (pi2 * x_float / np_f).cos() + c * (pi4 * x_float / np_f).cos()
            - d * (pi6 * x_float / np_f).cos();
    }
    window
}

/// Helper function. Standard Blackman window.
// The window created is periodic.
pub fn blackman<T>(npoints: usize) -> Vec<T>
where
    T: Float,
{
    let mut window = vec![T::zero(); npoints];
    let pi2 = T::from(2.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let pi4 = T::from(4.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let np_f = T::from(npoints).unwrap();
    let a = T::from(0.42).unwrap();
    let b = T::from(0.5).unwrap();
    let c = T::from(0.08).unwrap();
    for (x, item) in window.iter_mut().enumerate() {
        let x_float = T::from(x).unwrap();
        *item = a - b * (pi2 * x_float / np_f).cos() + c * (pi4 * x_float / np_f).cos();
    }
    window
}

/// Helper function. Standard Hann window.
// The window created is periodic.
pub fn hann<T>(npoints: usize) -> Vec<T>
where
    T: Float,
{
    // trace!("Making a Hann windows with {} points", npoints);
    let mut window = vec![T::zero(); npoints];
    let pi2 = T::from(2.0).unwrap() * T::from(std::f64::consts::PI).unwrap();
    let np_f = T::from(npoints).unwrap();
    let a = T::from(0.5).unwrap();
    for (x, item) in window.iter_mut().enumerate() {
        let x_float = T::from(x).unwrap();
        *item = a - a * (pi2 * x_float / np_f).cos();
    }
    window
}

/// Make the selected window function.
pub fn make_window<T>(npoints: usize, windowfunc: WindowFunction) -> Vec<T>
where
    T: Float,
{
    let mut window = match windowfunc {
        WindowFunction::BlackmanHarris | WindowFunction::BlackmanHarris2 => {
            blackman_harris::<T>(npoints)
        }
        WindowFunction::Blackman | WindowFunction::Blackman2 => blackman::<T>(npoints),
        WindowFunction::Hann | WindowFunction::Hann2 => hann::<T>(npoints),
    };
    match windowfunc {
        WindowFunction::Blackman2 | WindowFunction::BlackmanHarris2 | WindowFunction::Hann2 => {
            window.iter_mut().for_each(|y| *y = *y * *y);
        }
        _ => {}
    };
    window
}

/// Calculate a suitable relative cutoff frequency for the given sinc length using the given window function.
/// The result is based on an approximation, which gives good results for sinc lengths from 32 to 2048.
pub fn calculate_cutoff<T>(npoints: usize, windowfunc: WindowFunction) -> T
where
    T: Float,
{
    // Coefficient values generated by cutoff_fit_cubic.py
    let (k1, k2, k3) = match windowfunc {
        WindowFunction::BlackmanHarris => (
            T::from(8.041443677716476).unwrap(),
            T::from(55.9506779343387).unwrap(),
            T::from(898.0287985384213).unwrap(),
        ),
        WindowFunction::BlackmanHarris2 => (
            T::from(13.745202940783823).unwrap(),
            T::from(121.73532586374934).unwrap(),
            T::from(5964.163279612051).unwrap(),
        ),
        WindowFunction::Blackman => (
            T::from(6.159598046201173).unwrap(),
            T::from(18.926415097606878).unwrap(),
            T::from(653.4247430458968).unwrap(),
        ),
        WindowFunction::Blackman2 => (
            T::from(9.506235102129398).unwrap(),
            T::from(79.13120634953742).unwrap(),
            T::from(1502.2316160588925).unwrap(),
        ),
        WindowFunction::Hann => (
            T::from(3.3481080887677166).unwrap(),
            T::from(10.106519434875038).unwrap(),
            T::from(78.96345249024414).unwrap(),
        ),
        WindowFunction::Hann2 => (
            T::from(5.38751148378734).unwrap(),
            T::from(29.69451915489501).unwrap(),
            T::from(184.82117462266237).unwrap(),
        ),
    };
    let one = T::one();
    one / (k1 / T::from(npoints).unwrap()
        + k2 / T::from(npoints.pow(2)).unwrap()
        + k3 / T::from(npoints.pow(3)).unwrap()
        + one)
}

pub(crate) fn validate_buffers<T: Float>(
    input: &impl BlockRead<T>,
    output: &mut impl BlockWrite<T>,
    channels: u16,
    min_input_frames: u32,
    min_output_frames: u32,
) -> Result<(), &'static str> {
    if input.num_channels() != channels {
        return Err("ResampleError::WrongNumberOfInputChannels");
    }
    if input.num_frames() < min_input_frames {
        return Err("ResampleError::InsufficientInputFrameSize");
    }
    if output.num_channels() != channels {
        return Err("ResampleError::WrongNumberOfOutputChannels");
    }
    if output.num_frames() < min_output_frames {
        return Err("ResampleError::InsufficientOutputFrameSize");
    }
    Ok(())
}

/// Helper function: sinc(x) = sin(pi*x)/(pi*x).
pub fn sinc<T>(value: T) -> T
where
    T: Float,
{
    if value == T::zero() {
        T::one()
    } else {
        (value * T::from(std::f64::consts::PI).unwrap()).sin()
            / (value * T::from(std::f64::consts::PI).unwrap())
    }
}

/// Helper function. Make a set of windowed sincs.
pub fn make_sincs<T>(
    npoints: usize,
    factor: usize,
    f_cutoff: f32,
    windowfunc: WindowFunction,
) -> Vec<Vec<T>>
where
    T: Float,
{
    let totpoints = npoints * factor;
    let mut y = Vec::with_capacity(totpoints);
    let window = make_window::<T>(totpoints, windowfunc);
    let mut sum = T::zero();
    for (x, w) in window.iter().enumerate().take(totpoints) {
        let val = *w
            * sinc(
                (T::from(x).unwrap() - T::from(totpoints / 2).unwrap())
                    * T::from(f_cutoff).unwrap()
                    / T::from(factor).unwrap(),
            );
        sum = sum + val;
        y.push(val);
    }
    sum = sum / T::from(factor).unwrap();
    // debug!(
    //     "Generate sincs, length: {}, oversampling: {}, normalized by: {:?}",
    //     npoints, factor, sum
    // );
    let mut sincs = vec![vec![T::zero(); npoints]; factor];
    for p in 0..npoints {
        for n in 0..factor {
            sincs[factor - n - 1][p] = y[factor * p + n] / sum;
        }
    }
    sincs
}

pub fn validate_sample_rates(input: usize, output: usize) -> Result<(), ()> {
    if input == 0 || output == 0 {
        return Err(());
    }
    Ok(())
}
