[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "neort-floats"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = ["std"]
std = []

[dev-dependencies]
criterion = { workspace = true }
num-traits = { workspace = true }

[[bench]]
name = "floats"
harness = false
